# Generated by Django 2.0.2 on 2018-08-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=200)),
                ('stock_quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('expected_arrival_date', models.DateTimeField()),
            ],
        ),
    ]
