# Generated by Django 2.0.2 on 2018-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='product_name',
            field=models.CharField(default='model_name', max_length=50),
            preserve_default=False,
        ),
    ]
