# Generated by Django 2.0.2 on 2018-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_machinemodel_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-01'),
            preserve_default=False,
        ),
    ]
