# Generated by Django 2.1 on 2018-08-24 15:51

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180824_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='parts_used_to_make',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'part1': 3}),
            preserve_default=False,
        ),
    ]
